# -*- coding: utf-8 -*-
"""part1_data_prep.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rV5p95Y9fr8deJhFY4yguo7EavVImyKc
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Create a directory for plots if it doesn't exist to keep things organized
os.makedirs('plots', exist_ok=True)

def load_and_explore_data(filepath):
    print("--- Loading Dataset ---")
    df = pd.read_csv(filepath)
    print(f"Dataset Shape: {df.shape}")
    print("\nMissing Values Before Cleaning:")
    print(df.isnull().sum())
    return df

def clean_data(df):
    print("\n--- Cleaning Data ---")
    # The water potability dataset typically has missing values in ph, Sulfate, and Trihalomethanes.
    # We will impute these missing values using the median of each respective column.
    columns_to_impute = ['ph', 'Sulfate', 'Trihalomethanes']

    for col in columns_to_impute:
        if col in df.columns:
            median_value = df[col].median()
            df[col] = df[col].fillna(median_value)

    print("Missing Values After Cleaning:")
    print(df.isnull().sum())
    return df

def engineer_features(df):
    print("\n--- Engineering Features ---")
    # The assignment requires at least one categorical column.
    # Since this dataset is entirely numeric, we will engineer a categorical column
    # by binning the 'Hardness' feature into categories.

    bins = [0, 60, 120, 180, df['Hardness'].max()]
    labels = ['Soft', 'Moderate', 'Hard', 'Very Hard']

    df['Hardness_Category'] = pd.cut(df['Hardness'], bins=bins, labels=labels)
    print("New Categorical Column 'Hardness_Category' created.")
    print(df['Hardness_Category'].value_counts())

    return df

def generate_visualizations(df):
    print("\n--- Generating and Saving Visualizations ---")

    # 1. Distribution of the Target Variable (pH)
    plt.figure(figsize=(8, 5))
    sns.histplot(df['ph'], kde=True, color='blue', bins=30)
    plt.title('Distribution of Water pH Levels')
    plt.xlabel('pH Level')
    plt.ylabel('Frequency')
    plt.tight_layout()
    plt.savefig('plots/ph_distribution.png') # Mandatory per submission guidelines
    plt.close()
    print("Saved: plots/ph_distribution.png")

    # 2. Countplot of the Engineered Categorical Variable
    plt.figure(figsize=(8, 5))
    sns.countplot(data=df, x='Hardness_Category', palette='viridis')
    plt.title('Distribution of Water Hardness Categories')
    plt.xlabel('Hardness Category')
    plt.ylabel('Count')
    plt.tight_layout()
    plt.savefig('plots/hardness_category_counts.png') # Mandatory per submission guidelines
    plt.close()
    print("Saved: plots/hardness_category_counts.png")

    # 3. Correlation Heatmap (Numeric only)
    plt.figure(figsize=(10, 8))
    # Select only numeric columns for correlation to avoid errors
    numeric_df = df.select_dtypes(include=[np.number])
    correlation_matrix = numeric_df.corr()

    sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
    plt.title('Correlation Heatmap of Numeric Features')
    plt.tight_layout()
    plt.savefig('plots/correlation_heatmap.png') # Mandatory per submission guidelines
    plt.close()
    print("Saved: plots/correlation_heatmap.png")

def main():
    # Assuming the dataset is downloaded and placed in the same folder as water_potability.csv
    dataset_path = 'water_potability.csv'

    if not os.path.exists(dataset_path):
        print(f"Error: Could not find {dataset_path}. Please ensure it is in the same directory.")
        return

    # Execute the data pipeline
    raw_df = load_and_explore_data(dataset_path)
    cleaned_df = clean_data(raw_df)
    final_df = engineer_features(cleaned_df)
    generate_visualizations(final_df)

    # Save the processed dataset for Part 2 (Supervised Machine Learning)
    final_df.to_csv('processed_water_data.csv', index=False)
    print("\n--- Pipeline Complete ---")
    print("Processed dataset saved as 'processed_water_data.csv'. Ready for Part 2!")

if __name__ == "__main__":
    main()

import urllib.request

url = "https://raw.githubusercontent.com/jadanpl/Water-Potability-Prediction/main/water_potability.csv"
output_file = "water_potability.csv"

print("Downloading Water Quality Dataset...")
try:
    urllib.request.urlretrieve(url, output_file)
    print(f"Success! Saved as '{output_file}' in your current directory.")
except Exception as e:
    print(f"An error occurred: {e}")

# Create a directory for plots if it doesn't exist to keep things organized
os.makedirs('plots', exist_ok=True)

def load_and_explore_data(filepath):
    print("--- Loading Dataset ---")
    df = pd.read_csv(filepath)
    print(f"Dataset Shape: {df.shape}")
    print("\nMissing Values Before Cleaning:")
    print(df.isnull().sum())
    return df

def clean_data(df):
    print("\n--- Cleaning Data ---")
    # The water potability dataset typically has missing values in ph, Sulfate, and Trihalomethanes.
    # We will impute these missing values using the median of each respective column.
    columns_to_impute = ['ph', 'Sulfate', 'Trihalomethanes']

    for col in columns_to_impute:
        if col in df.columns:
            median_value = df[col].median()
            df[col] = df[col].fillna(median_value)

    print("Missing Values After Cleaning:")
    print(df.isnull().sum())
    return df

def engineer_features(df):
    print("\n--- Engineering Features ---")
    # The assignment requires at least one categorical column.
    # Since this dataset is entirely numeric, we will engineer a categorical column
    # by binning the 'Hardness' feature into categories.

    bins = [0, 60, 120, 180, df['Hardness'].max()]
    labels = ['Soft', 'Moderate', 'Hard', 'Very Hard']

    df['Hardness_Category'] = pd.cut(df['Hardness'], bins=bins, labels=labels)
    print("New Categorical Column 'Hardness_Category' created.")
    print(df['Hardness_Category'].value_counts())

    return df

def generate_visualizations(df):
    print("\n--- Generating and Saving Visualizations ---")

    # 1. Distribution of the Target Variable (pH)
    plt.figure(figsize=(8, 5))
    sns.histplot(df['ph'], kde=True, color='blue', bins=30)
    plt.title('Distribution of Water pH Levels')
    plt.xlabel('pH Level')
    plt.ylabel('Frequency')
    plt.tight_layout()
    plt.savefig('plots/ph_distribution.png') # Mandatory per submission guidelines
    plt.close()
    print("Saved: plots/ph_distribution.png")

    # 2. Countplot of the Engineered Categorical Variable
    plt.figure(figsize=(8, 5))
    sns.countplot(data=df, x='Hardness_Category', palette='viridis')
    plt.title('Distribution of Water Hardness Categories')
    plt.xlabel('Hardness Category')
    plt.ylabel('Count')
    plt.tight_layout()
    plt.savefig('plots/hardness_category_counts.png') # Mandatory per submission guidelines
    plt.close()
    print("Saved: plots/hardness_category_counts.png")

    # 3. Correlation Heatmap (Numeric only)
    plt.figure(figsize=(10, 8))
    # Select only numeric columns for correlation to avoid errors
    numeric_df = df.select_dtypes(include=[np.number])
    correlation_matrix = numeric_df.corr()

    sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
    plt.title('Correlation Heatmap of Numeric Features')
    plt.tight_layout()
    plt.savefig('plots/correlation_heatmap.png') # Mandatory per submission guidelines
    plt.close()
    print("Saved: plots/correlation_heatmap.png")

def main():
    # Assuming the dataset is downloaded and placed in the same folder as water_potability.csv
    dataset_path = 'water_potability.csv'

    if not os.path.exists(dataset_path):
        print(f"Error: Could not find {dataset_path}. Please ensure it is in the same directory.")
        return

    # Execute the data pipeline
    raw_df = load_and_explore_data(dataset_path)
    cleaned_df = clean_data(raw_df)
    final_df = engineer_features(cleaned_df)
    generate_visualizations(final_df)

    # Save the processed dataset for Part 2 (Supervised Machine Learning)
    final_df.to_csv('processed_water_data.csv', index=False)
    print("\n--- Pipeline Complete ---")
    print("Processed dataset saved as 'processed_water_data.csv'. Ready for Part 2!")

if __name__ == "__main__":
    main()

!wget https://raw.githubusercontent.com/jadanpl/Water-Potability-Prediction/main/water_potability.csv

from google.colab import drive
drive.mount('/content/drive')

from google.colab import userdata
api_key = userdata.get('LLM_API_KEY')

import requests
from google.colab import userdata

LLM_API_KEY = userdata.get("LLM_API_KEY")

# Safely fetch your key from Colab's secret vault
api_key = userdata.get('LLM_API_KEY')

# OpenRouter configuration
url = "https://openrouter.ai/api/v1/chat/completions"
headers = {
    "Authorization": f"Bearer {api_key}",
    "Content-Type": "application/json"
}

# The JSON body required by your assignment guidelines
data = {
    "model": "meta-llama/llama-3-8b-instruct:free", # You can use free models!
    "messages": [
        {"role": "user", "content": "Analyze this water quality metric..."}
    ]
}

# Sending the HTTP POST request
response = requests.post(url, headers=headers, json=data)
print(response.json())

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
import joblib

def load_and_prepare_data(filepath):
    print("--- Loading Cleaned Dataset ---")
    df = pd.read_csv(filepath)

    # Drop the 'Potability' column if it exists, as we are strictly predicting 'ph' (numeric target)
    if 'Potability' in df.columns:
        df = df.drop(columns=['Potability'])

    # Convert the engineered categorical 'Hardness_Category' into numeric dummy variables
    # This satisfies the requirement to handle categorical data in our ML pipeline
    df_encoded = pd.get_dummies(df, columns=['Hardness_Category'], drop_first=True)

    return df_encoded

def train_and_evaluate(df):
    print("\n--- Splitting Data into Train/Test Sets ---")
    # Define features (X) and target variable (y)
    X = df.drop(columns=['ph'])
    y = df['ph']

    # Split: 80% training, 20% testing
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    print("--- Training Random Forest Regressor ---")
    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)

    print("\n--- Evaluating Model Metrics ---")
    predictions = model.predict(X_test)

    mae = mean_absolute_error(y_test, predictions)
    rmse = np.sqrt(mean_squared_error(y_test, predictions))

    print(f"Mean Absolute Error (MAE): {mae:.4f}")
    print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")

    # Save the trained model file so we can use it in our intelligent system later
    joblib.dump(model, 'water_ph_model.pkl')
    print("\nTrained model saved successfully as 'water_ph_model.pkl'.")

def main():
    # Make sure 'processed_water_data.csv' from Part 1 is available in your workspace
    data_path = 'processed_water_data.csv'

    try:
        encoded_df = load_and_prepare_data(data_path)
        train_and_evaluate(encoded_df)
        print("\n--- Part 2 Pipeline Complete ---")
    except FileNotFoundError:
        print(f"Error: Could not find '{data_path}'. Make sure you ran Part 1 first.")

if __name__ == "__main__":
    main()